Repository virtru/virtuoso-design-system, pull requests merged in 2020-08, with the labels that each got.

#37 chore: resolve npm audit issue
  .eslintignore
  .eslintrc.js
  .github/workflows/run-on-pr.yml
  .lefthook/commit-msg/commit-linter
  .loki/reference/chrome_iphone7_Layout_typography_sticker_sheet.png
  .loki/reference/chrome_laptop_Layout_typography_sticker_sheet.png
  .stylelintignore
  .stylelintrc.js
  commitlint.config.js
  config/test.config.js
  jest.config.js
  lefthook.yml
  package-lock.json
  package.json
Labels: release

#42 Update contributors
  .all-contributorsrc
  README.md
Labels: documentation

#44 fix(design_tokens): add space between slash on font
  lib/styles/build/css/design_tokens.css
  lib/styles/build/js/design_tokens.js
  lib/styles/style_dict/tokens/font/fonts.json
Labels: minor, release

#52 build: add release workflow
  .github/workflows/deploy-storybook.yml
  .github/workflows/release.yml
  .github/workflows/validate-pr.yml
  package.json
Labels: patch, release

#55 build: fix storybook workflow
  .github/workflows/deploy-storybook.yml
  .github/workflows/release.yml
Labels: patch, release

#60 docs(example app): show design tokens & fonts in action
  examples/simple-app/index.css
  examples/simple-app/index.html
  examples/simple-app/index.js
  examples/simple-app/package.json
Labels: patch, release

#62 [PLAT-675] feat: add danger button
  .loki/reference/chrome_iphone7_Button_large.png
  .loki/reference/chrome_iphone7_Button_medium.png
  .loki/reference/chrome_iphone7_Button_number.png
  .loki/reference/chrome_iphone7_Button_small.png
  .loki/reference/chrome_iphone7_Button_square.png
  .loki/reference/chrome_laptop_Button_large.png
  .loki/reference/chrome_laptop_Button_medium.png
  .loki/reference/chrome_laptop_Button_number.png
  .loki/reference/chrome_laptop_Button_small.png
  .loki/reference/chrome_laptop_Button_square.png
  lib/components/Button/Button.css
  lib/components/Button/Button.js
  stories/vrc-stories/Button.js
Labels: minor, release

#63 feat(use-match-media): support ssr
  examples/.eslintrc
  lib/helpers/useMatchMedia.js
Labels: minor, release

#64 fix(use-match-media): support ssr window undefined
  lib/helpers/useMatchMedia.js
Labels: patch, release

#65 style(layout): center content
  .loki/reference/chrome_iphone7_Modal_large_no_footer_buttons.png
  .loki/reference/chrome_iphone7_Modal_large_with_footer_buttons.png
  .loki/reference/chrome_iphone7_Modal_small_no_content.png
  .loki/reference/chrome_iphone7_Modal_small_with_content.png
  .loki/reference/chrome_laptop_Layout_typography_sticker_sheet.png
  .loki/reference/chrome_laptop_Modal_large_no_footer_buttons.png
  .loki/reference/chrome_laptop_Modal_large_with_footer_buttons.png
  .loki/reference/chrome_laptop_Modal_small_no_content.png
  .loki/reference/chrome_laptop_Modal_small_with_content.png
  lib/components/Layout/styles/layout.css
Labels: minor, release

#68 docs: update links to new repository home
  README.md
  examples/simple-app/README.md
  examples/simple-app/index.css
  stories/Intro-design-tokens.stories.mdx
Labels: patch, release

#70 Fix deploy-storybook
  .github/workflows/deploy-storybook.yml
Labels: skip-release

#71 Update README.md
  CHANGELOG.md
  README.md
Labels: patch, release

#73 Chore redeploy 1.6.2 as 1.6.3 d
  CHANGELOG.md
  README.md
Labels: patch, release

#74 fix: correct danger button styles [PLAT-675]
  lib/components/Button/Button.css
Labels: patch, release
