Repository virtru/virtuoso-design-system, pull requests merged in 2021-02, with the labels that each got.

#122 Patch/remove barchart
  README.md
  lib/components/BarChart/BarChart.css
  lib/components/BarChart/BarChart.js
  lib/components/BarChart/components/CustomBar/CustomBar.css
  lib/components/BarChart/components/CustomBar/CustomBar.js
  lib/components/index.js
  package-lock.json
  package.json
  stories/vrc-stories/BarChart.js
Labels: bug, patch

#126 CCR-98 Remove min-width for the tooltip
  .loki/reference/chrome_iphone7_Tooltip_error.png
  .loki/reference/chrome_laptop_Tooltip_error.png
  lib/components/Tooltip/Tooltip.css
Labels: patch

#125 [CCR-124] chore: add data-testids to various elements
  lib/components/ChartContainer/ChartContainer.js
  lib/components/Paginator/Paginator.js
  lib/components/Paginator/components/Arrow/Arrow.js
  lib/components/PieChart/components/ArcsLayer/ArcsLayer.js
  lib/components/Table/Table.js
  lib/components/Table/components/TD/TD.js
  lib/components/Table/components/TH/TH.js
  lib/components/Table/components/TR/TR.js
Labels: patch

#127 CCR-98 Use use '[hash:base64]' classnames for production
  config/postcss.config.js
Labels: minor

#128 fix: use color for chart slice testid selector
  lib/components/PieChart/components/ArcsLayer/ArcsLayer.js
Labels: patch

#124 fix: add absolute positioning to content modal - CCR-17
  .loki/reference/chrome_iphone7_ContentModal_minimal.png
  .loki/reference/chrome_iphone7_ContentModal_no_icons.png
  .loki/reference/chrome_laptop_ContentModal_minimal.png
  .loki/reference/chrome_laptop_ContentModal_no_icons.png
  lib/components/ContentModal/ContentModal.css
  lib/components/ContentModal/ContentModal.js
  lib/components/Tabs/Tabs.css
  lib/components/Tabs/Tabs.js
  stories/vrc-stories/ContentModal.js
Labels: patch

#131 fix: use better selector for pie element
  lib/components/PieChart/components/ArcsLayer/ArcsLayer.js
Labels: patch

#132 chore: add codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: skip-release

#130 doc: update PR template
  .github/pull_request_template.md
Labels: documentation, skip-release
