Repository virtru/virtuoso-design-system, pull requests merged in 2021-12, with the labels that each got.

#239 [CCR-598] update nav
  .loki/reference/chrome_iphone7_virtru_navigation_basic.png
  .loki/reference/chrome_laptop_virtru_navigation_basic.png
  lib/components/dropdown/topMenuDropdown.css
  lib/components/dropdown/topMenuDropdown.js
  lib/components/dropdown/topMenuDropdownWrap.css
  lib/components/dropdown/topMenuDropdownWrap.js
  lib/components/layout/footer.css
  lib/components/layout/footer.js
  lib/components/layout/header.css
  lib/components/layout/header.js
  lib/components/layout/virtruLayout.css
  lib/components/layout/virtruLayout.js
  lib/components/navigation/demo/navigation.md
  lib/components/navigation/navItem.css
  lib/components/navigation/navItem.js
  lib/components/navigation/navigation.css
  lib/components/navigation/navigation.js
  lib/index.js
  stories/virtru/navigation/basic.jsx
Labels: enhancement, minor

#241 [CCR-598] update navitem style
  .loki/reference/chrome_iphone7_virtru_navigation_basic.png
  .loki/reference/chrome_laptop_virtru_navigation_basic.png
  lib/components/navigation/navItem.css
  lib/index.js
Labels: patch

#244 Feature/ccr 597
  .loki/reference/chrome_iphone7_virtru_spinner_loader.png
  .loki/reference/chrome_laptop_virtru_layout_top.png
  .loki/reference/chrome_laptop_virtru_layout_virtru_layout.png
  .loki/reference/chrome_laptop_virtru_spinner_loader.png
  lib/assets/illustration_loading.svg
  lib/components/layout/header.css
  lib/components/layout/header.js
  lib/components/spin/Loader.css
  lib/components/spin/Loader.js
  lib/index.js
  stories/virtru/spinner/loader.jsx
Labels: minor, release
