Repository virtru/virtuoso-design-system, pull requests merged in 2021-04, with the labels that each got.

#159 chore(deps): update react-select from 3.0.4 to 4.3.0
  package-lock.json
  package.json
Labels: patch, release

#162 chore(deps): changed react, react-dom peer dependencies
  package.json
Labels: patch, release

#165 CCR-77 Fix disabled state for Button and ChartContainer
  lib/components/Button/Button.css
  lib/components/ChartContainer/ChartContainer.js
  package-lock.json
  package.json
Labels: patch

#166 CCR-77 Fix chart container disabled title color
  .loki/reference/chrome_iphone7_ChartContainer_disabled.png
  .loki/reference/chrome_laptop_ChartContainer_disabled.png
  lib/components/ChartContainer/ChartContainer.css
  lib/components/ChartContainer/ChartContainer.js
  package-lock.json
  package.json
  stories/vrc-stories/ChartContainer.js
Labels: patch

#169 CCR-300 Add fixed table layout
  lib/components/Table/Table.css
  lib/components/Table/Table.js
Labels: minor

#173 CCR-291 Make content modal height 100%
  .loki/reference/chrome_iphone7_ContentModal_minimal.png
  .loki/reference/chrome_laptop_ContentModal_minimal.png
  lib/components/ContentModal/ContentModal.css
  lib/components/Tabs/Tabs.css
Labels: patch
