Repository virtru/virtuoso-design-system, pull requests merged in 2021-01, with the labels that each got.

#72 fix(design tokens): missing CSS var for shadow hover error
  lib/components/Layout/Layout.css
  lib/styles/build/css/design_tokens.css
  lib/styles/build/js/design_tokens.js
  lib/styles/style_dict/config.js
Labels: bug, release

#99 fix(chart-component): select width - CORE-1984
  .loki/reference/chrome_iphone7_ChartContainer_no_buttons.png
  .loki/reference/chrome_iphone7_ChartContainer_no_select.png
  .loki/reference/chrome_laptop_ChartContainer_minimal.png
  .loki/reference/chrome_laptop_ChartContainer_no_buttons.png
  .loki/reference/chrome_laptop_ChartContainer_no_select.png
  lib/components/ChartContainer/ChartContainer.css
  lib/components/Chevron/Chevron.css
  stories/vrc-stories/ChartContainer.js
Labels: patch

#100 CORE-2021 - Fix policy map legend colors
  .loki/reference/chrome_iphone7_PolicyMap_default.png
  .loki/reference/chrome_iphone7_PolicyMap_quartile_selected.png
  .loki/reference/chrome_laptop_PolicyMap_default.png
  .loki/reference/chrome_laptop_PolicyMap_quartile_selected.png
  lib/components/PolicyMap/PolicyMap.css
  stories/vrc-stories/PolicyMap.js
Labels: patch

#97 CORE-1982 - Bar chart component
  .eslintrc.js
  .loki/reference/chrome_iphone7_BarChart_Default.png
  .loki/reference/chrome_laptop_BarChart_Default.png
  lib/components/BarChart/BarChart.css
  lib/components/BarChart/BarChart.js
  lib/components/BarChart/components/CustomBar/CustomBar.css
  lib/components/BarChart/components/CustomBar/CustomBar.js
  package-lock.json
  package.json
  stories/vrc-stories/BarChart.js
Labels: minor

#96 chore: update pr template
  .github/pull_request_template.md
Labels: skip-release

#102 CCR-41: Make Chart container's Select searchable
  config/test.config.js
  lib/components/Select/Select.css.js
  lib/components/Select/Select.js
  lib/components/Select/Select.test.js
  package-lock.json
  package.json
  stories/vrc-stories/ChartContainer.js
Labels: minor

#103 fix(chevron): centering
  .loki/reference/chrome_laptop_ChartContainer_no_select.png
  lib/components/Chevron/Chevron.css
Labels: patch

#120 fix: exported BarChart from components
  lib/components/index.js
Labels: minor, release
