Repository virtru/virtuoso-design-system, pull requests merged in 2022-09, with the labels that each got.

#337 Fixed FileListItem component
  lib/components/fileListItem/fileListItem.css
  lib/components/fileListItem/fileListItem.js
Labels: patch, release

#343 Version bump: @draft-js-plugins/buttons with latest accessibility updates
  package-lock.json
  package.json
Labels: minor, patch

#342 #CCR-1352 Update Navigation Menu for Secure Share Mobile Sizes
  .loki/reference/chrome_iphone7_virtru_navigation_left.png
  lib/components/layout/virtruLayout.js
  lib/components/leftNavigation/leftNavigation.css
  lib/components/leftNavigation/leftNavigation.js
  stories/virtru/navigation/left.jsx
Labels: minor, release

#349 fix(version bump): adds accessibility label to link button for CCR-817
  package-lock.json
  package.json
Labels: minor
